  ${CF_FUNCTION_NAME}:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: ${MEMORY_SIZE}
      Timeout: ${TIMEOUT}
      FunctionName: ${FUNCTION_NAME}
      Handler: ${HANDLER}
      Role:
        Fn::ImportValue:
          !Sub "\${Environment}-CircuitsEngineRole"
      CodeUri:
        Bucket: !Ref DeployBucketName
        Key: ${FUNCTION_NAME}-${VERSION}.zip
      Environment:
        Variables:
          MD5: ${VERSION}
          FILES_BUCKET: !Ref FilesBucket
  ${CF_FUNCTION_NAME}ApiAttachResource:
    Type: "AWS::ApiGateway::Resource"
    DependsOn: ${ENV}CircuitsEngineDocumentAttachmentApiAttachResource
    Properties:
      ParentId: !Ref ${ENV}CircuitsEngineDocumentAttachmentApiAttachResource
      PathPart: \"{attachmentId}\"
      RestApiId: !Ref CircuitsEngineAPI
  ${CF_FUNCTION_NAME}ApiAttachResourceMethodGet:
    Type: "AWS::ApiGateway::Method"
    DependsOn: ${ENV}CircuitsEngineDocumentAttachmentApiAttachResource
    Properties:
      HttpMethod: \"GET\"
      OperationName: \"AttachmentGet\"
      ResourceId: !Ref ${CF_FUNCTION_NAME}ApiAttachResource
      RestApiId: !Ref CircuitsEngineAPI
      AuthorizationType: NONE
      RequestParameters:
              \"method.request.path.attachmentId\": true
      MethodResponses:
        -
          StatusCode: "200"
          ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
          ResponseModels:
              "image/png": Empty
              "image/jpg": Empty
              "application/pdf": Empty
        -
          StatusCode: "400"
          ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
          ResponseModels:
              "application/json": !Ref ApiGatewayErrorModel
        -
          StatusCode: "500"
          ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
          ResponseModels:
              "application/json": !Ref ApiGatewayErrorModel
      Integration:
        Type: "AWS_PROXY"
        Uri: !Sub arn:aws:apigateway:\${AWS::Region}:lambda:path/2015-03-31/functions/\${${CF_FUNCTION_NAME}.Arn}/invocations
        IntegrationResponses:
          -
            StatusCode: "200"
            ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,POST,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
        IntegrationHttpMethod: \"GET\"
  ${CF_FUNCTION_NAME}ApiAttachResourceMethodOptions:
    Type: "AWS::ApiGateway::Method"
    Properties:
      HttpMethod: \"OPTIONS\"
      OperationName: \"GetAttachmentOptions\"
      ResourceId: !Ref ${CF_FUNCTION_NAME}ApiAttachResource
      RestApiId: !Ref CircuitsEngineAPI
      AuthorizationType: NONE
      RequestParameters:
              \"method.request.path.attachmentId\": true
      MethodResponses:
        -
          StatusCode: "200"
          ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
          ResponseModels:
              "application/json": "Empty"
      Integration:
        Type: "MOCK"
        IntegrationResponses:
          -
            StatusCode: "200"
            ResponseParameters:
              \"method.response.header.Access-Control-Allow-Methods\": \"'GET,OPTIONS'\"
              \"method.response.header.Access-Control-Allow-Headers\": \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"
              \"method.response.header.Access-Control-Allow-Origin\": \"'*'\"
        RequestTemplates:
              application/json: \"{\\\"statusCode\\\": 200}\"
        PassthroughBehavior: \"when_no_match\"
        IntegrationHttpMethod: \"POST\"
        ContentHandling: CONVERT_TO_TEXT
  ${CF_FUNCTION_NAME}LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt ${CF_FUNCTION_NAME}.Arn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Join [\"\",[\"arn:aws:execute-api:\", !Ref \"AWS::Region\" , \":\", !Ref \"AWS::AccountId\", \":\", !Ref CircuitsEngineAPI, \"/*/GET/circuits/*/attachments/*\"]]
